services:
  part-5:
    container_name: ser
    build: .
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  proxy:
    container_name: pxy
    image: nginx:latest
    volumes: 
      - ./pxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080